---
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
      - -X github.com/kahnwong/ci-cd-utils/cmd.version={{.Version}}
checksum:
  disable: false
